#!/bin/sh

PYAUTO_AGGRESIVE="${PYAUTO_AGGRESIVE-1}"
PYAUTO_SCRICT="${PYAUTO_SCRICT-1}"

path="${1-.}"
if [ -f "$path" ]; then
    fns="$path"
else
    fns="$(find "$path" -name "*.py" -exec echo '"{}"' \;)"
fi

autopep8_options='--max-line-length 120'
autoflake_options=''

if [ "$PYAUTO_AGGRESIVE" = "1" ]; then
    autopep8_options="$autopep8_options
    --aggressive
    "
    # --expand-star-imports
    #                       expand wildcard star imports with undefined names;
    #                       this only triggers if there is only one star import in
    #                       the file; this is skipped if there are any uses of
    #                       `__all__` or `del` in the file
    # --remove-all-unused-imports
    #                       remove all unused imports (not just those from the
    #                       standard library)
    # --remove-duplicate-keys
    #                       remove all duplicate keys in objects
    # --remove-unused-variables
    #                       remove unused variables
    autoflake_options='
    --expand-star-imports
    --remove-all-unused-imports
    --remove-duplicate-keys
    --remove-unused-variables
    '

fi

die_if_strict()
{
    [ "$PYAUTO_SCRICT" = "1" ] && exit 1
}


die_if_changed()
{
    White="$(        tput bold; tput setaf 7)"
    NC="$(                      tput sgr0)"

    if [ "$PYAUTO_SCRICT" = "1" ]; then
        if git diff --name-only | grep -q "."; then
            git status

            echo "$White"
            echo "#### Something is auto fixed."
            echo "#### Please review and 'git add' them."
            echo "$NC"
            exit 1
        fi
    fi
}

eval autopep8  -i $autopep8_options        $fns
eval autoflake -i $autoflake_options       $fns
eval isort     --force-single-line-imports $fns
eval pyflakes                              $fns || die_if_strict

die_if_changed
